name: CI/CD Cloud Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gcr.io/$(GCP_PROJECT_ID)/$(IMAGE_NAME):$(GITHUB_SHA)
      env:
          IMAGE_NAME: iseven-as-a-service
          GCP_PROJECT_ID: react-gke-terraform
